name: Build
on:
  push:
  pull_request:

jobs:
  build:
    if: ${{ !startsWith(github.event.ref, 'refs/tags/') && contains(github.event.head_commit.message, '*') == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the sources
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ./.gradle/loom-caches
            ~/.gradle/wrapper
          key: ubuntu-gradle-${{ hashFiles('*.gradle', 'gradle.properties') }}
          restore-keys: ubuntu-gradle-

      - name: Read Properties of mod
        id: mod_info
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: "mod_name mod_version"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        env:
          BUILD_TYPE: "BETA"
        run: ./gradlew build

      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.mod_info.outputs.mod_name }} ${{ steps.mod_info.outputs.mod_version }}+{{ github.run_number }}
          path: |
            LICENSE
            versions/1.16.5/build/libs/*.jar
            versions/1.17.1/build/libs/*.jar
            versions/1.18.2/build/libs/*.jar
            versions/1.19.3/build/libs/*.jar
